# Generated by Django 3.2.7 on 2021-09-02 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('meal_eaten', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('review', models.TextField()),
            ],
        ),
    ]
