# Generated by Django 3.2.7 on 2021-09-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_meals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meallog',
            old_name='review',
            new_name='how_did_you_find_it',
        ),
    ]
