# Generated by Django 3.2.7 on 2021-09-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_meals', '0002_rename_review_meallog_how_did_you_find_it'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('meals_eaten', models.IntegerField()),
            ],
        ),
    ]
