# Generated by Django 3.2.7 on 2021-09-01 17:54

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[(recipes.models.MealTypes['FIRE'], 'Campfire Cooking'), (recipes.models.MealTypes['INDOORS'], 'Indoor Catering'), (recipes.models.MealTypes['SMALL'], 'Small Group Cooking')], default=recipes.models.MealTypes['INDOORS'], max_length=25),
        ),
    ]
