# Generated by Django 3.2.7 on 2021-09-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_recipe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='url_name',
            field=models.TextField(default=''),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients_list',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients_list',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
