# Generated by Django 3.2.7 on 2021-09-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210901_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='url_name',
            field=models.TextField(default='', max_length=40),
        ),
    ]
