# Generated by Django 3.2.7 on 2021-09-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_recipe_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('Campfire Cooking', 'FIRE'), ('Indoor Catering', 'INDOORS'), ('Small Group Cooking', 'SMALL')], max_length=25),
        ),
    ]
