# Generated by Django 3.2.7 on 2021-09-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_recipe_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('FIRE', 'Campfire Cooking'), ('INDOORS', 'Indoor Catering'), ('SMALL', 'Small Group Cooking')], max_length=25),
        ),
    ]
